### ISSUE TITLE
Unable to write to certain mapped memory

### ISSUE THREAD

**Issue by Dnawrkshp** [NzV/MAMBA#1]
When writing to memory mapped as executable but not listed as a segment in the eboot, PS3MAPI or rather copy_to_process fails to write.

As a possible solution, I'd suggest using the syscall sys_dbg_write_process_memory. A bit more info can be read here http://www.ps3devwiki.com/ps3/CCAPI#Installation and http://www.ps3devwiki.com/ps3/LV2_Functions_and_Syscalls#sys_dbg_Syscalls

**Comment by NzV** [comment]
Thanks for report it, i will take a look into this soon

**Comment by Dnawrkshp** [comment]
I use MAMBA since I'm not on cobra.

**Comment by NzV** [comment]
Sorry for delay, i have updated MAMBA today with support for CFW 4.75 and also made an minor change who will fix the writing error on some address.

**Comment by Dnawrkshp** [comment]
Funny I just looked at this only 10 minutes ago.
Awesome! I'll be sure to test it very soon. Thanks for the work!

**Comment by Dnawrkshp** [comment]
Unfortunately I can't seem to compile the payload even if I export PS3DEV to the one included with the payload.
If I could get the compiled payloads so I could test I'd appreciate it.

**Comment by NzV** [comment]
I have also updated MAMBA/PRX Loader you can find it here

**Comment by NzV** [comment]
I have also updated MAMBA/PRX Loader you can find it here

**Comment by Dnawrkshp** [comment]
I forgot to mention that I tested it and it still failed. I believe the section is a part of a prx loaded during runtime. Not sure if that'd help at all.
